# Generated by Django 4.0.6 on 2022-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
